FROM php:8.1-fpm

WORKDIR /var/www

EXPOSE 80
 
RUN apt-get update && apt-get install -y \
    apt-utils \
    libpq-dev \
    libpng-dev \
    libzip-dev \
    zip unzip \
    git && \
    docker-php-ext-install pdo_mysql && \
    docker-php-ext-install bcmath && \
    docker-php-ext-install gd && \
    docker-php-ext-install zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN useradd -ms /bin/bash admin

COPY ./_docker/app/php.ini /usr/local/etc/php/conf.d/php.ini

COPY . .

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- \
    --filename=composer \
    --install-dir=/usr/local/bin

RUN chown -R admin:admin storage
RUN chmod 777 *
RUN chmod -R 777 storage && chmod -R 777 bootstrap/cache
USER admin



